name: Docker Image Tag

on:
  push:
    tags:
      - 'latest'  # Match semantic versioning tags like v1.0.0

permissions:
  contents: write
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Determine Docker tag
      id: docker_tag
      run: |
        TAG=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')
        echo "::set-output name=tag::${TAG}"

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:Suspicious"
        push: true
        tags: ghcr.io/thalesgroup-cert/suspicious:${{ steps.docker_tag.outputs.tag }}

